tcms/testplans/urls.py
# -*- coding: utf-8 -*-

from django.urls import re_path

from tcms.testplans import views

urlpatterns = [
    re_path(
        r"^(?P<pk>\d+)/$",
        views.GetTestPlanRedirectView.as_view(),
        name="test_plan_url_short",
    ),
    # human friendly url
    re_path(
        r"^(?P<pk>\d+)/(?P<slug>[-\w\d]+)$",
        views.TestPlanGetView.as_view(),
        name="test_plan_url",
    ),
    re_path(r"^(?P<pk>\d+)/edit/$", views.Edit.as_view(), name="plan-edit"),
    re_path(r"^(?P<pk>\d+)/clone/$", views.Clone.as_view(), name="plans-clone"),
    re_path(r"^search/$", views.SearchTestPlanView.as_view(), name="plans-search"),
    re_path(r"^new/$", views.NewTestPlanView.as_view(), name="plans-new"),
]

tcms/urls.py
# -*- coding: utf-8 -*-
from importlib import import_module

import pkg_resources
from attachments import urls as attachments_urls
from captcha import urls as captcha_urls
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import re_path
from django.views.generic import TemplateView
from django.views.i18n import JavaScriptCatalog
from grappelli import urls as grappelli_urls
from modernrpc.core import Protocol
from modernrpc.views import RPCEntryPoint

from tcms.core import views as core_views
from tcms.kiwi_auth import urls as auth_urls
from tcms.telemetry import urls as telemetry_urls
from tcms.testcases import urls as testcases_urls
from tcms.testplans import urls as testplans_urls
from tcms.testruns import urls as testruns_urls

urlpatterns = [
    re_path(r"^$", core_views.DashboardView.as_view(), name="core-views-index"),
    re_path(r"^captcha/", include(captcha_urls)),
    re_path(r"^xml-rpc/", RPCEntryPoint.as_view(protocol=Protocol.XML_RPC)),
    re_path(r"^json-rpc/$", RPCEntryPoint.as_view(protocol=Protocol.JSON_RPC)),
    re_path(r"^init-db/$", core_views.InitDBView.as_view(), name="init-db"),
    re_path(
        r"^translation-mode/",
        core_views.TranslationMode.as_view(),
        name="translation-mode",
    ),
    re_path(r"^grappelli/", include(grappelli_urls)),
    re_path(r"^admin/", admin.site.urls),
    re_path(r"^attachments/", include(attachments_urls, namespace="attachments")),
    # Account information zone, such as login method
    re_path(r"^accounts/", include(auth_urls)),
    # Testplans zone
    re_path(r"^plan/", include(testplans_urls)),
    # Testcases zone
    re_path(r"^case/", include(testcases_urls.case_urls)),
    re_path(r"^cases/", include(testcases_urls.cases_urls)),
    # Testruns zone
    re_path(r"^runs/", include(testruns_urls)),
    re_path(r"^telemetry/", include(telemetry_urls)),
    # JavaScript translations, see
    # https://docs.djangoproject.com/en/2.1/topics/i18n/translation/#django.views.i18n.JavaScriptCatalog
    re_path(r"^jsi18n/$", JavaScriptCatalog.as_view(), name="javascript-catalog"),
]


# conditional import b/c this App can be disabled
if "tcms.bugs.apps.AppConfig" in settings.INSTALLED_APPS:
    from tcms.bugs import urls as bugs_urls

    urlpatterns.append(re_path(r"^bugs/", include(bugs_urls)))


for plugin in pkg_resources.iter_entry_points("kiwitcms.plugins"):
    plugin_urls = import_module(f"{plugin.module_name}.urls")
    urlpatterns.append(re_path(f"^{plugin.name}/", include(plugin_urls)))


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns.extend(
        [
            re_path(r"^500/$", TemplateView.as_view(template_name="500.html")),
            re_path(r"^404/$", TemplateView.as_view(template_name="404.html")),
        ]
    )

    try:
        import debug_toolbar

        urlpatterns += [
            re_path(r"^__debug__/", include(debug_toolbar.urls)),
        ]
    # in case we're trying to debug in production
    # and debug_toolbar is not installed
    except ImportError:
        pass


# Overwrite default 500 handler
# More details could see django.core.urlresolvers._resolve_special()
handler500 = "tcms.core.views.server_error"

tcms/testplans/models.py
# -*- coding: utf-8 -*-

from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from django.urls import reverse
from tree_queries.models import TreeNode
from uuslug import slugify

from tcms.core.history import KiwiHistoricalRecords
from tcms.core.models.base import UrlMixin
from tcms.core.templatetags.extra_filters import bleach_input
from tcms.management.models import Version
from tcms.testcases.models import TestCasePlan


class PlanType(models.Model, UrlMixin):
    name = models.CharField(max_length=64, unique=True)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["name"]


class TestPlan(TreeNode, UrlMixin):
    """A plan within the TCMS"""

    history = KiwiHistoricalRecords()

    name = models.CharField(max_length=255, db_index=True)
    text = models.TextField(blank=True)
    create_date = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True, db_index=True)
    extra_link = models.CharField(max_length=1024, default=None, blank=True, null=True)

    product_version = models.ForeignKey(
        Version, related_name="plans", on_delete=models.CASCADE
    )
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey(
        "management.Product", related_name="plan", on_delete=models.CASCADE
    )
    type = models.ForeignKey(PlanType, on_delete=models.CASCADE)
    tag = models.ManyToManyField(
        "management.Tag", through="testplans.TestPlanTag", related_name="plan"
    )

    def __str__(self):
        return self.name

    def add_case(self, case, sortkey=None):
        if sortkey is None:
            lastcase = self.testcaseplan_set.order_by("-sortkey").first()
            if lastcase and lastcase.sortkey is not None:
                sortkey = lastcase.sortkey + 10
            else:
                sortkey = 0

        return TestCasePlan.objects.get_or_create(
            plan=self, case=case, defaults={"sortkey": sortkey}
        )[0]

    def add_tag(self, tag):
        return TestPlanTag.objects.get_or_create(plan=self, tag=tag)

    def remove_tag(self, tag):
        TestPlanTag.objects.filter(plan=self, tag=tag).delete()

    def delete_case(self, case):
        TestCasePlan.objects.filter(case=case.pk, plan=self.pk).delete()

    def _get_absolute_url(self):
        return reverse("test_plan_url", args=[self.pk, slugify(self.name)])

    def get_absolute_url(self):
        return self._get_absolute_url()

    def get_full_url(self):
        return super().get_full_url().rstrip("/")

    def _get_email_conf(self):
        try:
            # note: this is the reverse_name of a 1-to-1 field
            return self.email_settings  # pylint: disable=no-member
        except ObjectDoesNotExist:
            return TestPlanEmailSettings.objects.create(plan=self)

    emailing = property(_get_email_conf)

    def make_cloned_name(self):
        """Make default name of cloned plan"""
        return f"Copy of {self.name}"

    def clone(  # pylint: disable=too-many-arguments
        self,
        name=None,
        product=None,
        version=None,
        new_author=None,
        set_parent=False,
        copy_testcases=False,
        **_kwargs,
    ):
        """Clone this plan

        :param name: New name of cloned plan. If not passed, make_cloned_name is called
            to generate a default one.
        :type name: str
        :param product: Product of cloned plan. If not passed, original plan's product is used.
        :type product: :class:`tcms.management.models.Product`
        :param version: Product version of cloned plan. If not passed use from source plan.
        :type version: :class:`tcms.management.models.Version`
        :param new_author: New author of cloned plan. If not passed, original plan's
            author is used.
        :type new_author: settings.AUTH_USER_MODEL
        :param set_parent: Whether to set original plan as parent of cloned plan.
            Default is False.
        :type set_parent: bool
        :param copy_testcases: Whether to copy cases to cloned plan instead of just
            linking them. Default is False.
        :type copy_testcases: bool
        :param \\**_kwargs: Unused catch-all variable container for any extra input
            which may be present
        :return: cloned plan
        :rtype: :class:`tcms.testplans.models.TestPlan`
        """
        tp_dest = TestPlan.objects.create(
            name=name or self.make_cloned_name(),
            product=product or self.product,
            author=new_author or self.author,
            type=self.type,
            product_version=version or self.product_version,
            create_date=self.create_date,
            is_active=self.is_active,
            extra_link=self.extra_link,
            parent=self if set_parent else None,
            text=self.text,
        )

        # Copy the plan tags
        for tp_tag_src in self.tag.all():
            tp_dest.add_tag(tag=tp_tag_src)

        # include TCs inside cloned TP
        qs = self.cases.all().annotate(sortkey=models.F("testcaseplan__sortkey"))
        for tc_src in qs:
            # this parameter should really be named clone_testcases b/c if set
            # it clones the source TC and then adds it to the new TP
            if copy_testcases:
                tc_src.clone(new_author, [tp_dest])
            else:
                # otherwise just link the existing TC to the new TP
                tp_dest.add_case(tc_src, sortkey=tc_src.sortkey)

        return tp_dest

    def tree_as_list(self):
        """
        Returns the entire tree family as a list of TestPlan
        object with additional fields from tree_queries!
        """
        plan = TestPlan.objects.with_tree_fields().get(pk=self.pk)

        tree_root = plan.ancestors(include_self=True).first()
        result = tree_root.descendants(include_self=True)

        return result

    def tree_view_html(self):
        """
        Returns nested tree structure represented as Patterfly TreeView!
        Relies on the fact that tree nodes are returned in DFS
        order!
        """
        tree_nodes = self.tree_as_list()

        # TP is not part of a tree
        if len(tree_nodes) == 1:
            return ""

        result = ""
        previous_depth = -1

        for test_plan in tree_nodes:
            # close tags for previously rendered node before rendering current one
            if test_plan.tree_depth == previous_depth:
                result += """
                    </div><!-- end-subtree -->
                </div> <!-- end-node -->"""

            # indent
            previous_depth = max(test_plan.tree_depth, previous_depth)

            # outdent
            did_outdent = False
            while test_plan.tree_depth < previous_depth:
                result += """
                    </div><!-- end-subtree -->
                </div> <!-- end-node -->"""
                previous_depth -= 1
                did_outdent = True

            if did_outdent:
                result += """
                    </div><!-- end-subtree -->
                </div> <!-- end-node -->"""

            # render the current node
            active_class = ""
            if test_plan.pk == self.pk:
                active_class = "active"

            plan_name = bleach_input(test_plan.name)
            result += f"""
                <!-- begin-node -->
                <div class="list-group-item {active_class}" style="border: none">
                    <div class="list-group-item-header" style="padding:0">
                        <div class="list-view-pf-main-info"
                             style="padding-top:0; padding-bottom:0">
                            <div class="list-view-pf-left"
                                 style="margin-left:3px; padding-right:10px">
                                <span class="fa fa-angle-right"></span>
                            </div>

                            <div class="list-view-pf-body">
                                <div class="list-view-pf-description">
                                    <div class="list-group-item-text">
                                        <a href="{test_plan.get_absolute_url()}">
                                            TP-{test_plan.pk}: {plan_name}
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div> <!-- /header -->

                    <!-- begin-subtree -->
                    <div class="list-group-item-container container-fluid" style="border: none">
            """

        # close after the last elements in the for loop
        while previous_depth >= 0:
            result += """
                    </div><!-- end-subtree -->
                </div> <!-- end-node -->"""
            previous_depth -= 1

        # HTML sanity check
        begin_node = result.count("<!-- begin-node -->")
        end_node = result.count("<!-- end-node -->")

        begin_subtree = result.count("<!-- begin-subtree -->")
        end_subtree = result.count("<!-- end-subtree -->")

        # tese will make sure that we catch errors in production
        if begin_node != end_node:
            raise RuntimeError("Begin/End count for tree-view nodes don't match")

        if begin_subtree != end_subtree:
            raise RuntimeError("Begin/End count for tree-view subtrees don't match")

        return f"""
            <div id="test-plan-family-tree"
                 class="list-group tree-list-view-pf"
                 style="margin-top:0">
                {result}
            </div>
        """


class TestPlanTag(models.Model):
    tag = models.ForeignKey("management.Tag", on_delete=models.CASCADE)

tcms/rpc/api/forms/testplan.py
from django import forms

from tcms.rpc.api.forms import UpdateModelFormMixin
from tcms.testplans.forms import NewPlanForm
from tcms.testplans.models import PlanType


class EditPlanForm(
    UpdateModelFormMixin, NewPlanForm
):  # pylint: disable=remove-empty-class,too-many-ancestors
    pass


class PlanTypeForm(forms.ModelForm):
    class Meta:
        model = PlanType
        fields = "__all__"

tcms/testplans/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.forms import inlineformset_factory

from tcms.core.forms.fields import UserField
from tcms.core.widgets import SimpleMDE
from tcms.management.models import Product, Version
from tcms.testplans.models import TestPlan, TestPlanEmailSettings


class NewPlanForm(forms.ModelForm):
    class Meta:
        model = TestPlan
        exclude = ("tag",)  # pylint: disable=modelform-uses-exclude

    text = forms.CharField(widget=SimpleMDE(), required=False)

    def populate(self, product_id):
        if product_id:
            self.fields["product_version"].queryset = Version.objects.filter(
                product_id=product_id
            )
        else:
            self.fields["product_version"].queryset = Version.objects.all()


# note: these fields can't change during runtime !
_email_settings_fields = []  # pylint: disable=invalid-name
for field in TestPlanEmailSettings._meta.fields:
    _email_settings_fields.append(field.name)


# for usage in CreateView, UpdateView
PlanNotifyFormSet = inlineformset_factory(  # pylint: disable=invalid-name
    TestPlan,
    TestPlanEmailSettings,
    fields=_email_settings_fields,
    can_delete=False,
    can_order=False,
)


class SearchPlanForm(forms.ModelForm):
    class Meta:
        model = TestPlan
        fields = "__all__"

    # overriden widget
    author = UserField()

    # extra fields
    default_tester = UserField()

    def populate(self, product_id=None):
        if product_id:
            self.fields["product_version"].queryset = Version.objects.filter(
                product_id=product_id
            )
        else:
            self.fields["product_version"].queryset = Version.objects.none()


class ClonePlanForm(forms.Form):  # pylint: disable=must-inherit-from-model-form
    name = forms.CharField(required=True)

    product = forms.ModelChoiceField(
        queryset=Product.objects.all(),
        empty_label=None,
    )
    version = forms.ModelChoiceField(
        queryset=Version.objects.none(),
        empty_label=None,
    )

    copy_testcases = forms.BooleanField(required=False)
    set_parent = forms.BooleanField(required=False)

    def populate(self, product_pk):
        if product_pk:
            self.fields["version"].queryset = Version.objects.filter(
                product_id=product_pk
            )
        else:
            self.fields["version"].queryset = Version.objects.none()

tcms/testplans/templates/testplans/clone.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block title %}{% trans "Clone TestPlan" %} - {{ test_plan.name }}{% endblock %}
{% block page_id %}page-testplans-mutable{% endblock %}

{% block contents %}
<div class="container-fluid container-cards-pf">
    <form class="form-horizontal" method="post" action="{% url "plans-clone" object.pk %}">
        {% csrf_token %}

        <div class="form-group">
            <label class="col-md-1 col-lg-1" for="id_name">{% trans "Name" %}</label>
            <div class="col-md-3 col-lg-3 {% if form.name.errors %}has-error{% endif %}">
                <input type="text" id="id_name" name="name" value="{{ form.name.value|default:'' }}" class="form-control" required>
                {{ form.name.errors }}
            </div>

            <div class="col-md-1 col-lg-1">
                <label for="id_product">{% trans "Product" %}</label>
                <a href="{% url 'admin:management_product_add' %}?_popup" id="add_id_product" alt="{% trans 'add new Product' %}" title="{% trans 'add new Product' %}">+</a>
            </div>
            <div class="col-md-3 col-lg-3 {% if form.product.errors %}has-error{% endif %}">
                <select id="id_product" name="product" class="form-control selectpicker">
                    {% for product in form.product.field.queryset %}
                        <option value="{{ product.pk }}" {% if product.pk|escape == form.product.value|escape %}selected{% endif %}>
                            {{ product.name }}
                        </option>
                    {% endfor %}
                </select>
                {{ form.product.errors }}
            </div>

            <div class="col-md-1 col-lg-1">
                <label for="id_version">{% trans "Version" %}</label>
                <a href="{% url 'admin:management_version_add' %}?_popup&product={{ form.product.value }}"
                   id="add_id_version" alt="{% trans 'add new Version' %}" title="{% trans 'add new Version' %}">
                    +
                </a>
            </div>
            <div class="col-md-3 col-lg-3 {% if form.version.errors %}has-error{% endif %}">
                <select id="id_version" name="version" class="form-control selectpicker">
                    {% for product_version in form.version.field.queryset %}
                        <option value="{{ product_version.pk }}" {% if product_version.pk|escape == form.version.value|escape %}selected{% endif %}>
                            {{ product_version.value }}
                        </option>
                    {% endfor %}
                </select>
                {{ form.version.errors }}
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-1 col-lg-1" for="id_copy_testcases">{% trans "Clone TCs" %}</label>
            <div class="col-md-3 col-lg-3">
                <input class="bootstrap-switch" id="id_copy_testcases" name="copy_testcases"
                           type="checkbox" {% if form.copy_testcases.value %}checked{% endif %} data-on-text="{% trans 'Yes' %}" data-off-text="{% trans 'No' %}">
                <p class="help-block">{% trans "Clone or link existing TCs into new TP" %}</p>
            </div>


            <label class="col-md-1 col-lg-1" for="id_set_parent">{% trans "Parent TP" %}</label>
            <div class="col-md-3 col-lg-3">
                <input class="bootstrap-switch" id="id_set_parent" name="set_parent"
                       type="checkbox"  {% if form.set_parent.value %}checked{% endif %} data-on-text="{% trans 'Yes' %}" data-off-text="{% trans 'No' %}">
                <p class="help-block">{% trans "Set the source TP as parent of new TP" %}</p>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-1 col-lg-1">
                <button type="submit" class="btn btn-default btn-lg">{% trans "Clone" %}</button>
            </div>
        </div>
    </form>

</div><!-- /container -->
{% endblock %}

tcms/testplans/templates/testplans/search.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block title %}{% trans "Search Test Plans" %}{% endblock %}
{% block page_id %}page-testplans-search{% endblock %}

{% block contents %}
<div
    class="container-fluid container-cards-pf"
    id="main-element"
    data-trans-some-rows-not-shown="{% trans 'Some child test plans do not match search criteria'%}"
>
    <form class="form-horizontal" method="get">
        {% csrf_token %}

        <div class="form-group">
            <label class="col-md-1 col-lg-1" for="id_name">{% trans "Name" %}</label>
            <div class="col-md-3 col-lg-3">
                <input id="id_name" type="text" class="form-control" placeholder="{% trans 'Test plan name' %}"
                    value="{{ form.name.value|default:'' }}">
            </div>

            <label class="col-md-1 col-lg-1">{% trans "Created" %}</label>
            <div class="col-md-3 col-lg-3">
                <div class="input-group date-time-picker-pf">
                    <span class="input-group-addon">{% trans "Before" %}</span>
                    <input type="text" class="form-control" id="id_before">
                    <span class="input-group-addon">
                        <span class="fa fa-calendar"></span>
                    </span>

                    <span class="input-group-addon">{% trans "After" %}</span>
                    <input type="text" class="form-control" id="id_after">
                    <span class="input-group-addon">
                        <span class="fa fa-calendar"></span>
                    </span>
                </div>
            </div>

            <label class="col-md-1 col-lg-1" for="id_active">{% trans "Active" %}</label>
            <div class="col-md-3 col-lg-3">
                <input class="bootstrap-switch" id="id_active" type="checkbox"
                    checked data-on-text="{% trans 'Yes' %}" data-off-text="{% trans 'No' %}"
                    value="{{ form.is_active.value }}">
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-1 col-lg-1" for="id_product">{% trans "Product" %}</label>
            <div class="col-md-3 col-lg-3">
                <select class="form-control selectpicker" id="id_product">
                    <option value="">----------</option>
                {% for option in form.product.field.queryset %}
                    <option value="{{ option.pk }}" {% if form.product.value|add:'0' == option.pk %}selected{% endif %}>{{ option.name }}</option>
                {% endfor %}
                </select>
            </div>

            <label class="col-md-1 col-lg-1" for="id_version">{% trans "Version" %}</label>
            <div class="col-md-3 col-lg-3">
                <select class="form-control selectpicker" id="id_version">
                    <option value="">----------</option>
                {% for option in form.product_version.field.queryset %}
                    <option value="{{ option.pk }}" {% if form.product_version.value|add:'0' == option.pk %}selected{% endif %}>{{ option.value }}</option>
                {% endfor %}
                </select>
            </div>

            <label class="col-md-1 col-lg-1" for="id_type">{% trans "Type" %}</label>
            <div class="col-md-3 col-lg-3">
                <select class="form-control selectpicker" id="id_type">
                    <option value="">----------</option>
                {% for option in form.type.field.queryset %}
                    <option value="{{ option.pk }}" {% if form.type.value|add:'0' == option.pk %}selected{% endif %}>{{ option.name }}</option>
                {% endfor %}
                </select>
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-1 col-lg-1" for="id_author">{% trans "Author" %}</label>
            <div class="col-md-3 col-lg-3">
                <input id="id_author" type="text" class="form-control" placeholder="{% trans 'Username' %}"
                    value="{{ form.author.value|default:'' }}">
            </div>

            <label class="col-md-1 col-lg-1" for="id_default_tester">{% trans "Default tester" %}</label>
            <div class="col-md-3 col-lg-3">
                <input id="id_default_tester" type="text" class="form-control" placeholder="{% trans 'Username' %}"
                    value="{{ form.default_tester.value|default:'' }}">
            </div>

            <label class="col-md-1 col-lg-1" for="id_tag">{% trans "Tag" %}</label>
            <div class="col-md-3 col-lg-3">
                <input id="id_tag" type="text" class="form-control" value="{{ form.tag.value.0|default:'' }}">
                <p class="help-block">{% trans "Separate multiple values with comma (,)" %}</p>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-1 col-lg-1">
                <button id="btn_search" type="submit" class="btn btn-default btn-lg">{% trans "Search" %}</button>
            </div>
        </div>
    </form>

    <div class="panel panel-default">
        <!-- Table HTML -->
        <table class="table table-striped table-bordered table-hover" id="resultsTable">
            <thead>
                <tr>
                    <th></th>
                    <th>{% trans "ID" %}</th>
                    <th>{% trans "Test plan" %}</th>
                    <th>{% trans "Created on" %}</th>
                    <th>{% trans "Product" %}</th>
                    <th>{% trans "Version" %}</th>
                    <th>{% trans "Type" %}</th>
                    <th>{% trans "Author" %}</th>
                    <th>{% trans "Tags" %}</th>
                </tr>
            </thead>
        </table>

    </div>
</div><!-- /container -->
{% endblock %}

tcms/testplans/templates/testplans/toolbar_dropdown.html
{% load i18n %}

<li class="{{ first_class }}" data-filter-type="summary"><a href="#">{% trans 'Summary' %}</a></li>
<li data-filter-type="case_status__name"><a href="#">{% trans 'Status' %}</a></li>
<li data-filter-type="is_automated"><a href="#">{% trans 'Automated' %}</a></li>
<li data-filter-type="priority__value"><a href="#">{% trans 'Priority' %}</a></li>
<li data-filter-type="category__name"><a href="#">{% trans 'Category' %}</a></li>
<li data-filter-type="author__username"><a href="#">{% trans 'Author' %}</a></li>
<li data-filter-type="default_tester__username"><a href="#">{% trans 'Default tester' %}</a></li>
<li data-filter-type="reviewer__username"><a href="#">{% trans 'Reviewer' %}</a></li>